### ISSUE TITLE
Cannot update UZB7 Firmware

### ISSUE THREAD

**Issue by vaderag** [SiliconLabs/gecko_sdk#18]
I have the right firmware from this package and have attempted to flash OTW using PC Controller, following instructions here: [Z-Wave 700/800: OTW of Controller - Silicon Labs (silabs.com)](https://community.silabs.com/s/article/z-wave-700-otw-of-controller?language=en_US)

I received an error "can't open Xmodem session"

This is not a devkit device so I shouldn't need a bootloader, nevertheless I have attempted to follow those instruction and the terminal in TeraTerm does not allow any interaction (per here, stuck at Step 5: https://siliconlabs.force.com/community/s/article/z-wave-700-programming-uzb7-controller-stick?language=en_US)

Can someone please assist with this?

**Comment by sloeffler-mkl** [comment]
Which file did you use? For flashing 700 UZB sticks you should use the GBL file for EFR32ZG14 if any or a respective board number (like BRD4206A)?

**Comment by vaderag** [comment]
I'm using the right firmware ([this one](https://github.com/SiliconLabs/gecko_sdk/raw/v4.0.2/protocol/z-wave/Apps/bin/gbl/ZW_SerialAPI_Controller_7_17_2_406_EFR32ZG14_REGION_EU.gbl))

But I get this error
![image](https://user-images.githubusercontent.com/17175988/185939654-134b4cf1-b31a-4436-96d0-6896420bec09.png)

**Comment by LanKuoWei** [comment]
I think your 700 UZB sticks have some issue need re-program firmware, I would suggest you to use jlink to update your UZB-7,  because I otw 7.16-> 7.17 -> 7.18 is fine, no any fail message.

![7 17](https://user-images.githubusercontent.com/71474070/186290619-61ebbec3-ea6a-4e43-bcd9-9c753fe8e9eb.jpg)

![7 18](https://user-images.githubusercontent.com/71474070/186290646-9c56ab9b-5c1a-4df4-bbd4-b17b4848d772.jpg)

**Comment by vaderag** [comment]
> I think your 700 UZB sticks have some issue need re-program firmware, I would suggest you to use jlink to update your UZB-7, because I otw 7.16-> 7.17 -> 7.18 is fine, no any fail message.
> 
> ![7 17](https://user-images.githubusercontent.com/71474070/186290619-61ebbec3-ea6a-4e43-bcd9-9c753fe8e9eb.jpg)
> 
> ![7 18](https://user-images.githubusercontent.com/71474070/186290646-9c56ab9b-5c1a-4df4-bbd4-b17b4848d772.jpg)

Thanks, but I also get problems when trying to do that...
I followed instructions here: https://community.silabs.com/s/article/z-wave-700-otw-of-controller?language=en_US
Got everything ready
![image](https://user-images.githubusercontent.com/17175988/186358296-1c4b7275-69e6-44da-96b1-62bbb0070f0d.png)

However, when I try and run the commands as advised I get the following
![image](https://user-images.githubusercontent.com/17175988/186358390-0b3e6a18-542f-4721-8f1e-c06b92d279c0.png)

I also attempted installing the J-link drivers in the Simplicity package , which did not make a difference

**Comment by LanKuoWei** [comment]
Because UZB-7 put USB port driver is CP210X,
not J-link, if you need this J-link, need check this UZB-7 board have 
J-link connect,
this guide's command line is only use by J-link connect and send command.


like in my pc-controller:


but kb's guide is:



However UZB-7 only need use PC-Controller to OTW,
don't do the other thing to upgrade,
sorry I can't help you to continue test,
because I can't have the same message.

I suggest you create case to ask support,
that have quick the teach you how to get correct way.



vaderag 於 2022/8/24 下午 03:33 寫道:

**Comment by vaderag** [comment]
I've done it... the driver must have been corrupt or something - since you mentioned it above I decided to remove it entirely. Re-installed (from the same package I installed it from fwiw) and then suddenly everything was working
